### ISSUE TITLE
Grpcx::Server - make class, not a mixin?

### ISSUE THREAD

**Issue by mxmCherry** [bsm/grpcx#4]
I think, that usual usage pattern of this gem is / will be like:

```ruby
class MyServer < Grpclb::Server
  include Grpcx::Server
end
```

Roughly, nothing new is added, just need to create own class for every project.

Probably, it's worth to do the following:
1. Rename `Grpcx::Server` -> `Grpcx::ServerMixin` (or `...::ServerExt` or whatever sounds better) or even make it private (see item below)
2. Make a real `class Grpcx::Server < Grpclb::Server; include Grpcx::ServerMixin; end`

So when you import `grpcx`, you don't need to write a server class, you just do:

```ruby
server = Grpcx::Server.new(...)
server.add_http2_port(...)
server.handle(...)
server.run_till_terminated
```

What I mean - probably, this gem doesn't have to be a mixin, but an opinionated gRPC server implementation?

It still will be open for extension - like `rescue_from` etc.

**Comment by dim** [comment]
sure, pls PR

**Comment by mxmCherry** [comment]
No need to do it. Better keep it as a mixin and, probably, turn grpclb into a mixin as well, so users can do:

```
class MyServer < GRPC::RpcServer
  include Grpcx::Server
  include Grpclb::Server
  ...
end
```
